name: Android CI(Pixie-Control)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: scene5

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: set up JDK 17
        add-to-path: false

    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      # run: ./gradlew build
      run: ./gradlew assembleRelease

    - name: Upload GitHub Actions artifact of vcpkg build
      uses: actions/upload-artifact@v2
      with:
        name: Pixie-Control-dev
        path: ${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk

    - name: Deploy
      env: 
        GITHUB_REPO: https://github.com/PIXIE-KEVIN/Pixie-Control
      run: |
        cd ${{ github.workspace }}/app/build/outputs/apk/release/
        git init
        git config user.name "KEVIN_PIXIE_CORP"
        git config user.email "kr337909@gmail.com"
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" master:master
